In [1]:
import torch
print(torch.__version__)

2.10.0+cu128


In [2]:
if torch.cuda.is_available():
  print("GPU is avialble")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available. Using CPU")

GPU is avialble
Using GPU: Tesla T4


In [3]:
# CREATING A TENSOR

In [6]:
# USing an empty

a = torch.empty(2,3)

In [7]:
print(a)

tensor([[-2.2265e-19,  4.4435e-41,  8.3727e-14],
        [ 0.0000e+00,  2.0000e+00,  8.1492e-03]])


In [8]:
# Check type

In [9]:
type(a)

torch.Tensor

In [11]:
#Using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [12]:
#Using ones

torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [13]:
#using rand

In [14]:
torch.rand(2,3)

tensor([[0.0956, 0.9038, 0.8576],
        [0.6886, 0.3550, 0.3986]])

In [15]:
#manual_seed - rand tensor remain same

In [16]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [17]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [18]:
# using tensor

torch.tensor([1,2,3])

tensor([1, 2, 3])

In [19]:
#OTHER WAYS

#arange
print("Using arange - ", torch.arange(0,10,2))

#using linspace
print("Using linspace ", torch.linspace(0,10,10))

#using eye
print("using eye ", torch.eye(5))

#using full
print("Using full ", torch.full((3,5),5))

Using arange -  tensor([0, 2, 4, 6, 8])
Using linspace  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Using full  tensor([[5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5]])


In [20]:
# Tensor Shapes


In [21]:
x=torch.tensor([[1,2,3],[4,5,6]])

In [22]:
print(x)
print(x.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


In [23]:
torch.empty_like(x)

tensor([[700248416, 618332336,         0],
        [        0,         1,         0]])

In [24]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [25]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [35]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [26]:
#Tensor Datatypes

In [27]:
x.dtype

torch.int64

In [28]:
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [29]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [30]:
# USING TO

In [32]:
a=x.to(torch.float32)
print(a)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [33]:
a.to(torch.int32)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [36]:
# MATHEMATICAL OPERATIONS

In [37]:
# 1. SCALAR OPERATIONS

In [38]:
x=torch.rand(2,2)

In [39]:
print(x)

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])


In [43]:
#addition
x+2

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])

In [44]:
#subtraction
x-3

tensor([[-2.2882, -2.2124],
        [-2.5817, -2.0986]])

In [45]:
#multiplication
x*4

tensor([[2.8471, 3.1503],
        [1.6732, 3.6057]])

In [46]:
x/2

tensor([[0.3559, 0.3938],
        [0.2092, 0.4507]])

In [48]:
#int divison
(x*100)//2

tensor([[35., 39.],
        [20., 45.]])

In [49]:
#mod
((x*100)//3)%2

tensor([[1., 0.],
        [1., 0.]])

In [50]:
#power
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

In [51]:
# 2. Element wise operation
a=torch.rand(2,3)
b=torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [52]:
a+b

tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])

In [53]:
a-b

tensor([[ 0.4411, -0.2205, -0.2201],
        [-0.6455, -0.5661,  0.3346]])

In [54]:
a*b

tensor([[0.5540, 0.7391, 0.0994],
        [0.2866, 0.1328, 0.4030]])

In [55]:
a/b

tensor([[1.7938, 0.7743, 0.5042],
        [0.3190, 0.2397, 1.6841]])

In [56]:
a**b

tensor([[0.9983, 0.7614, 0.5145],
        [0.3218, 0.2771, 0.9096]])

In [57]:
a%b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [58]:
c=torch.tensor([1,-2,3,-4])

In [60]:
#abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [61]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [62]:
d=torch.tensor([1.9,2.3,3.7,4.4])

In [65]:
#round
torch.round(d)
#ceil


tensor([2., 2., 4., 4.])

In [66]:
torch.ceil(d)



tensor([2., 3., 4., 5.])

In [67]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [68]:
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

In [74]:
# 3.Reduction operation
e=torch.randint(size=(2,3) , low=0, high=10, dtype=torch.float32)

In [75]:
print(e)

tensor([[5., 7., 3.],
        [9., 4., 0.]])


In [76]:
#sum
torch.sum(e)
#sum along columns

#sum along rows


tensor(28.)

In [77]:
torch.sum(e,dim=0)

tensor([14., 11.,  3.])

In [78]:
torch.sum(e,dim=1)

tensor([15., 13.])

In [79]:
torch.mean(e)

tensor(4.6667)

In [80]:
# mean along col
torch.mean(e,dim=0)

tensor([7.0000, 5.5000, 1.5000])

In [81]:
torch.median(e)

tensor(4.)

In [83]:
torch.max(e)

tensor(9.)

In [84]:

torch.min(e)

tensor(0.)

In [85]:
# product
torch.prod(e)

tensor(0.)

In [86]:
#SD
torch.std(e)

tensor(3.1411)

In [88]:
#variance

torch.var(e)

tensor(9.8667)

In [89]:
#argmax
torch.argmax(e)

tensor(3)

In [90]:
#argmin
torch.argmin(e)

tensor(5)

In [91]:
# matrix operations


In [93]:
f=torch.randint(size=(2,3), low=0, high=10)
g=torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[5, 7, 5],
        [9, 9, 7]])
tensor([[5, 9],
        [8, 9],
        [7, 9]])


In [94]:
# MATRIX MULTIPLY
torch.matmul(f,g)

tensor([[116, 153],
        [166, 225]])

In [95]:
vector1=torch.tensor([1,2])
vector2=torch.tensor([3,4])

In [96]:
print(vector1)
print(vector2)

tensor([1, 2])
tensor([3, 4])


In [97]:
torch.dot(vector1,vector2)

tensor(11)

In [98]:
#transpose
print(f)

tensor([[5, 7, 5],
        [9, 9, 7]])


In [99]:
torch.transpose(f,0,1)

tensor([[5, 9],
        [7, 9],
        [5, 7]])

In [104]:
h=torch.randint(size=(3,3), low=0,high=10, dtype=torch.float32)
print(h)

tensor([[5., 0., 4.],
        [3., 8., 8.],
        [3., 3., 5.]])


In [105]:
#det, #inv
torch.det(h)

tensor(20.0000)

In [106]:
torch.inverse(h)

tensor([[ 0.8000,  0.6000, -1.6000],
        [ 0.4500,  0.6500, -1.4000],
        [-0.7500, -0.7500,  2.0000]])

In [107]:
#COMPARISION OPERATIONS

In [108]:
i=torch.randint(size=(2,3),low=0,high=10)
j=torch.randint(size=(2,3),low=0,high=10  )

In [109]:
print(i)
print(j)

tensor([[0, 6, 4],
        [0, 8, 4]])
tensor([[7, 2, 3],
        [8, 5, 6]])


In [110]:
i>j

tensor([[False,  True,  True],
        [False,  True, False]])

In [111]:
i<j

tensor([[ True, False, False],
        [ True, False,  True]])

In [112]:
i==j

tensor([[False, False, False],
        [False, False, False]])

In [113]:
i!=j

tensor([[True, True, True],
        [True, True, True]])

In [121]:
# 6. Special Functions

k=torch.randint(size=(2,3),low=0,high=10, dtype=torch.float32)

In [122]:
k

tensor([[7., 1., 1.],
        [5., 4., 4.]])

In [123]:
#log
torch.log(k)

tensor([[1.9459, 0.0000, 0.0000],
        [1.6094, 1.3863, 1.3863]])

In [124]:
#exp
torch.exp(k)

tensor([[1096.6332,    2.7183,    2.7183],
        [ 148.4132,   54.5981,   54.5981]])

In [125]:
#sqrt
torch.sqrt(k)

tensor([[2.6458, 1.0000, 1.0000],
        [2.2361, 2.0000, 2.0000]])

In [126]:
#sigmoid
torch.sigmoid(k)

tensor([[0.9991, 0.7311, 0.7311],
        [0.9933, 0.9820, 0.9820]])

In [127]:
#softmax
torch.softmax(k,dim=0)

tensor([[0.8808, 0.0474, 0.0474],
        [0.1192, 0.9526, 0.9526]])

In [128]:
#relu
torch.relu(k)

tensor([[7., 1., 1.],
        [5., 4., 4.]])

In [129]:
#INPLACE OPERATIONS


In [130]:
m=torch.rand(2,3)
n=torch.rand(2,3)

print(m)
print(n)

tensor([[0.1780, 0.3011, 0.1893],
        [0.9186, 0.2131, 0.3957]])
tensor([[0.6017, 0.4234, 0.5224],
        [0.4175, 0.0340, 0.9157]])


In [131]:
m+n # New tesnor formed more memory usage

tensor([[0.7796, 0.7245, 0.7117],
        [1.3361, 0.2472, 1.3114]])

In [132]:
m.add_(n)

tensor([[0.7796, 0.7245, 0.7117],
        [1.3361, 0.2472, 1.3114]])

In [133]:
m

tensor([[0.7796, 0.7245, 0.7117],
        [1.3361, 0.2472, 1.3114]])

In [134]:
n

tensor([[0.6017, 0.4234, 0.5224],
        [0.4175, 0.0340, 0.9157]])

In [136]:
torch.relu(m)

tensor([[0.7796, 0.7245, 0.7117],
        [1.3361, 0.2472, 1.3114]])

In [137]:
m.relu_() # For permament change place underscore after a fun

tensor([[0.7796, 0.7245, 0.7117],
        [1.3361, 0.2472, 1.3114]])

In [138]:
#COPY A TENSOR

In [139]:
a=torch.rand(2,3)

In [140]:
a

tensor([[0.3079, 0.6269, 0.8277],
        [0.6594, 0.0887, 0.4890]])

In [141]:
b=a # refrence

In [142]:
b

tensor([[0.3079, 0.6269, 0.8277],
        [0.6594, 0.0887, 0.4890]])

In [143]:
a[0][0]=0
print(a)
print(b)

tensor([[0.0000, 0.6269, 0.8277],
        [0.6594, 0.0887, 0.4890]])
tensor([[0.0000, 0.6269, 0.8277],
        [0.6594, 0.0887, 0.4890]])


In [145]:
id(a)


136190043364224

In [146]:
id(b)

136190043364224

In [148]:
#clone()

b=a.clone()


In [149]:
print(a)
print(b)

tensor([[0.0000, 0.6269, 0.8277],
        [0.6594, 0.0887, 0.4890]])
tensor([[0.0000, 0.6269, 0.8277],
        [0.6594, 0.0887, 0.4890]])


In [150]:
a[0][0]=10
print(a)
print(b)

tensor([[10.0000,  0.6269,  0.8277],
        [ 0.6594,  0.0887,  0.4890]])
tensor([[0.0000, 0.6269, 0.8277],
        [0.6594, 0.0887, 0.4890]])


In [151]:
print(id(a))
print(id(b))

136190043364224
136190041722144


# **TENSOR OPERATIONS ON GPU**

In [152]:
torch.cuda.is_available()

True

In [153]:
device = torch.device('cuda')

In [154]:
#creating tensor on gpu
torch.rand((2,3),device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [ ]:
#moving existing tensor from cpu to gpu

In [155]:
print(a)

tensor([[10.0000,  0.6269,  0.8277],
        [ 0.6594,  0.0887,  0.4890]])


In [157]:
b = a.to(device)

In [158]:
print(b)

tensor([[10.0000,  0.6269,  0.8277],
        [ 0.6594,  0.0887,  0.4890]], device='cuda:0')


In [159]:
b+5

tensor([[15.0000,  5.6269,  5.8277],
        [ 5.6594,  5.0887,  5.4890]], device='cuda:0')

In [160]:
import time

size=10000

matrix_cpu1=torch.randn(size,size)
matrix_cpu2=torch.randn(size,size)


#time on cpu
start_time=time.time()
result_cpu=torch.matmul(matrix_cpu1,matrix_cpu2)
cpu_time=time.time()-start_time
print(f"Time taken by cpu {cpu_time}")

#move matrices to GPU
matrix_cpu1=matrix_cpu1.to('cuda')
matrix_cpu2=matrix_cpu2.to('cuda')

#Measure time on GPU
start_time=time.time()
result_gpu=torch.matmul(matrix_cpu1,matrix_cpu2)
torch.cuda.synchronize()
gpu_time=time.time()-start_time
print(f"Time taken by gpu {gpu_time}")

print("\nSpeedup (CPU /GPU TIME ):", cpu_time/gpu_time)

Time taken by cpu 15.61160135269165
Time taken by gpu 0.6907150745391846

Speedup (CPU /GPU TIME ): 22.602085763231734


# **RESAPING TENSORS**

In [161]:
a=torch.ones(4,4)

In [162]:
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [163]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [164]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [167]:
b=torch.rand(2,3,4)

In [168]:
b

tensor([[[0.8243, 0.2861, 0.7459, 0.8487],
         [0.4059, 0.2883, 0.2220, 0.6423],
         [0.7098, 0.5644, 0.4549, 0.0729]],

        [[0.8535, 0.9793, 0.0611, 0.1162],
         [0.7666, 0.8801, 0.4203, 0.8186],
         [0.0463, 0.7306, 0.2009, 0.3265]]])

In [169]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [170]:
c=torch.rand(226,226,3)

In [171]:
c

tensor([[[0.6684, 0.3509, 0.7772],
         [0.2353, 0.4301, 0.4385],
         [0.7375, 0.5494, 0.7109],
         ...,
         [0.9161, 0.3424, 0.8958],
         [0.4974, 0.3637, 0.4017],
         [0.3999, 0.8137, 0.5557]],

        [[0.1924, 0.3498, 0.2113],
         [0.1764, 0.7310, 0.5387],
         [0.7520, 0.6309, 0.2384],
         ...,
         [0.8021, 0.0467, 0.3780],
         [0.8288, 0.8384, 0.5071],
         [0.4687, 0.6338, 0.1352]],

        [[0.6763, 0.8780, 0.6078],
         [0.7377, 0.5412, 0.3477],
         [0.6434, 0.1762, 0.1385],
         ...,
         [0.4764, 0.5963, 0.0442],
         [0.7153, 0.2716, 0.2348],
         [0.7881, 0.2544, 0.1470]],

        ...,

        [[0.0911, 0.1087, 0.5137],
         [0.1784, 0.8197, 0.2613],
         [0.2057, 0.4454, 0.8809],
         ...,
         [0.0768, 0.2541, 0.6531],
         [0.2220, 0.7911, 0.4496],
         [0.1167, 0.1556, 0.7784]],

        [[0.0546, 0.7405, 0.0703],
         [0.9499, 0.0688, 0.1863],
         [0.

In [174]:
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [175]:
d=torch.rand(1,20)
d

tensor([[0.6179, 0.1797, 0.3512, 0.0083, 0.1996, 0.9616, 0.6520, 0.2396, 0.8719,
         0.0902, 0.7858, 0.1384, 0.1220, 0.6667, 0.8944, 0.9877, 0.0938, 0.7860,
         0.5388, 0.0125]])

In [176]:
d.squeeze(0).shape

torch.Size([20])

# **NumPy and PyTorch**

In [177]:
import numpy as np

In [178]:
a=torch.tensor([1,2,3])

In [179]:
a

tensor([1, 2, 3])

In [180]:
b=a.numpy()

In [181]:
b

array([1, 2, 3])

In [182]:
type(b)

numpy.ndarray

In [183]:
type(a)

torch.Tensor

In [184]:
c=np.array([1,2,3])
c

array([1, 2, 3])

In [185]:
torch.from_numpy(c)

tensor([1, 2, 3])